(()=>{'use strict';
const $=id=>document.getElementById(id), q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
const USER_LABELS={administrador:'Administrador',assistencia:'Assistência',comercial:'Comercial',rui_ferreira:'Rui Ferreira',joao_rebelo:'João Rebelo',sandro_loureiro:'Sandro Loureiro'};
const SELLER_MAP={rui_ferreira:'RUI FERREIRA',joao_rebelo:'JOÃO REBELO',sandro_loureiro:'SANDRO LOUREIRO'};
const currentUser=sessionStorage.getItem('dmCurrentUser')||''; const isAdmin=['assistencia','administrador'].includes(currentUser);
let sb=null, connected=false, salesRows=[], clients=[], opportunities=[], activities=[], profiles=[], settings={};
const defaults={statuses:['Novo','Enviada','Negociação','Perdida','Hot Deal','Pronta a faturar','Ganho'],priorities:['Baixa','Normal','Alta','Urgente'],activity_types:['Telefonema','Email','Reunião','Visita','Tarefa','Assistência'],loss_reasons:['Preço','Sem resposta','Concorrência','Prazo','Outro'],reminders:{Enviada:15,Perdida:15,'Hot Deal':10,'Pronta a faturar':5}};
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function money(v){return new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}).format(Number(v)||0)}
function norm(v){return String(v??'').trim().toLocaleUpperCase('pt-PT')}
function setup(){ $('userBadge').textContent=USER_LABELS[currentUser]||'Sessão não identificada'; if(!currentUser){location.href='../index.html';return} qa('.admin-only').forEach(x=>x.classList.toggle('hidden-role',!isAdmin)); bindTabs(); $('modalClose').onclick=closeModal; $('modal').onclick=e=>{if(e.target===$('modal'))closeModal()}; init(); }
function bindTabs(){qa('#tabs button').forEach(b=>b.onclick=()=>{qa('#tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');qa('.view').forEach(x=>x.classList.remove('active'));$('view-'+b.dataset.view).classList.add('active');render(b.dataset.view)})}
async function init(){const cfg=window.DM_SUPABASE||{};if(cfg.url&&cfg.anonKey&&window.supabase){sb=window.supabase.createClient(cfg.url,cfg.anonKey);connected=true}else{$('setupBanner').classList.remove('hidden');$('setupBanner').innerHTML='<b>Supabase ainda não configurado.</b> Preencha <code>CRM/supabase-config.js</code> e execute <code>supabase-schema.sql</code>. A interface pode ser consultada, mas criar, editar ou eliminar fica bloqueado para evitar dados guardados apenas no navegador.'}await Promise.all([loadSales(),loadAll()]);render('dashboard')}
async function loadSales(){try{const r=await fetch('../Vendas_preenchido_062026.xlsx',{cache:'no-store'});if(!r.ok)return;const buf=await r.arrayBuffer();const wb=XLSX.read(buf,{type:'array'});salesRows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});deriveClients()}catch(e){console.warn(e)}}
function deriveClients(){const map=new Map();for(const r of salesRows){const name=r.CLIENTES||r.Clientes;if(!name)continue;const nif=String(r.CONTRIBUINTE||'').trim();const key=nif||norm(name);if(!map.has(key))map.set(key,{source_key:key,name:String(name).trim(),nif,email:r.EMAIL||'',phone:r.TELEMOVEL||'',district:r.DISTRITO||'',owner_name:r.VENDEDOR||r.COMERCIAL||'',source:'Excel de vendas'})}clients=[...map.values()]}
async function loadAll(){if(!connected)return;try{const [o,a,p,s,c]=await Promise.all([sb.from('crm_opportunities').select('*').order('created_at',{ascending:false}),sb.from('crm_activities').select('*').order('starts_at',{ascending:true}),sb.from('crm_profiles').select('*').order('display_name'),sb.from('crm_settings').select('*'),sb.from('crm_clients').select('*').order('name')]);if(o.error)throw o.error;opportunities=o.data||[];activities=a.data||[];profiles=p.data||[];settings=Object.fromEntries((s.data||[]).map(x=>[x.key,x.value]));const dbClients=c.data||[];const merged=new Map(clients.map(x=>[x.source_key,x]));dbClients.forEach(x=>merged.set(x.source_key||x.id,{...merged.get(x.source_key),...x,source:'Supabase'}));clients=[...merged.values()]}catch(e){bannerError(e.message)}}
function bannerError(m){$('setupBanner').classList.remove('hidden');$('setupBanner').innerHTML='<b>Erro no Supabase:</b> '+esc(m)}
function getCfg(k){return settings[k]||defaults[k]}
function ownRows(rows,field='owner_id'){if(isAdmin)return rows;return rows.filter(x=>x[field]===currentUser)}
function render(view){({dashboard:renderDashboard,opportunities:renderOpps,clients:renderClients,activities:renderActivities,calendar:renderCalendar,settings:renderSettings}[view]||(()=>{}))()}
function renderDashboard(){const mine=ownRows(opportunities),open=mine.filter(x=>!['Ganho','Perdida'].includes(x.status)),won=mine.filter(x=>x.status==='Ganho');$('view-dashboard').innerHTML=`<div class="grid kpis"><div class="card kpi"><span>Oportunidades</span><strong>${mine.length}</strong></div><div class="card kpi"><span>Em aberto</span><strong>${open.length}</strong></div><div class="card kpi"><span>Ganhas</span><strong>${won.length}</strong></div><div class="card kpi"><span>Pipeline</span><strong>${money(open.reduce((s,x)=>s+Number(x.value||0),0))}</strong></div><div class="card kpi"><span>Clientes disponíveis</span><strong>${clients.length}</strong></div></div><div class="panel" style="margin-top:16px"><h2>Próximas atividades</h2>${activityTable(ownRows(activities).slice(0,10))}</div>`}
function renderOpps(){const statuses=getCfg('statuses');const rows=ownRows(opportunities);$('view-opportunities').innerHTML=`<div class="toolbar"><h2>Oportunidades</h2><button id="newOpp" class="accent">+ Nova oportunidade</button></div><div class="kanban">${statuses.map(st=>`<div class="lane" data-status="${esc(st)}"><div class="lane-head"><span>${esc(st)}</span><span>${rows.filter(x=>x.status===st).length}</span></div>${rows.filter(x=>x.status===st).map(oppCard).join('')}</div>`).join('')}</div>`;$('newOpp').onclick=()=>editOpp();qa('.opp').forEach(x=>{x.onclick=()=>editOpp(x.dataset.id);x.draggable=true;x.ondragstart=e=>e.dataTransfer.setData('text/plain',x.dataset.id)});qa('.lane').forEach(l=>{l.ondragover=e=>e.preventDefault();l.ondrop=e=>moveOpp(e.dataTransfer.getData('text/plain'),l.dataset.status)})}
function oppCard(o){return `<article class="opp" data-id="${o.id}"><h3>${esc(o.title)}</h3><p>${esc(o.client_name||'Sem cliente')}</p><p>${money(o.value)} · ${esc(o.priority||'Normal')}</p><span class="badge">${esc(o.owner_name||o.owner_id||'')}</span></article>`}
async function moveOpp(id,status){if(!connected)return needConfig();const o=opportunities.find(x=>String(x.id)===String(id));if(!o||(!isAdmin&&o.owner_id!==currentUser))return;const {error}=await sb.from('crm_opportunities').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(error)return alert(error.message);await loadAll();renderOpps()}
function editOpp(id){if(!connected)return needConfig();const o=opportunities.find(x=>String(x.id)===String(id))||{};openModal(id?'Editar oportunidade':'Nova oportunidade',`<div class="form-grid"><div class="field full"><label>Título</label><input name="title" required value="${esc(o.title)}"></div><div class="field"><label>Cliente</label><input name="client_name" list="clientList" value="${esc(o.client_name)}"><datalist id="clientList">${clients.slice(0,3000).map(c=>`<option value="${esc(c.name)}">`).join('')}</datalist></div><div class="field"><label>Valor</label><input name="value" type="number" step="0.01" value="${o.value||0}"></div><div class="field"><label>Estado</label><select name="status">${getCfg('statuses').map(x=>`<option ${x===o.status?'selected':''}>${esc(x)}</option>`).join('')}</select></div><div class="field"><label>Prioridade</label><select name="priority">${getCfg('priorities').map(x=>`<option ${x===o.priority?'selected':''}>${esc(x)}</option>`).join('')}</select></div><div class="field"><label>Responsável</label>${ownerSelect(o.owner_id)}</div><div class="field"><label>Data prevista</label><input name="expected_close" type="date" value="${o.expected_close||''}"></div><div class="field full"><label>Notas</label><textarea name="notes">${esc(o.notes)}</textarea></div></div><div class="form-actions">${id?'<button type="button" id="deleteRecord" class="danger">Eliminar</button>':''}<button type="button" class="secondary" onclick="document.getElementById('modalClose').click()">Cancelar</button><button class="accent">Guardar</button></div>`,async data=>{const payload={...data,value:Number(data.value)||0,owner_id:isAdmin?(data.owner_id||currentUser):currentUser,owner_name:USER_LABELS[isAdmin?(data.owner_id||currentUser):currentUser]||data.owner_id,updated_at:new Date().toISOString()};const res=id?await sb.from('crm_opportunities').update(payload).eq('id',id):await sb.from('crm_opportunities').insert(payload);if(res.error)throw res.error});if(id)$('deleteRecord').onclick=()=>deleteRow('crm_opportunities',id,'oportunidade')}
function ownerSelect(selected){const ps=profiles.length?profiles:Object.entries(USER_LABELS).map(([id,display_name])=>({id,display_name,active:true}));if(!isAdmin)return `<input type="hidden" name="owner_id" value="${currentUser}"><input disabled value="${esc(USER_LABELS[currentUser])}">`;return `<select name="owner_id">${ps.filter(x=>x.active!==false).map(x=>`<option value="${x.id}" ${x.id===(selected||currentUser)?'selected':''}>${esc(x.display_name)}</option>`).join('')}</select>`}
function renderClients(){const rows=clients;$('view-clients').innerHTML=`<div class="toolbar"><h2>Clientes</h2><div class="toolbar-group"><input id="clientSearch" placeholder="Pesquisar cliente…"><button id="newClient" class="accent">+ Criar cliente</button></div></div><div class="panel table-wrap" id="clientTable">${clientTable(rows.slice(0,300))}</div>`;$('clientSearch').oninput=e=>{$('clientTable').innerHTML=clientTable(rows.filter(x=>norm(Object.values(x).join(' ')).includes(norm(e.target.value))).slice(0,500));bindClientRows()};$('newClient').onclick=()=>editClient();bindClientRows()}
function clientTable(rows){return `<table><thead><tr><th>Cliente</th><th>NIF</th><th>Distrito</th><th>Telefone</th><th>Email</th><th>Responsável</th><th>Origem</th></tr></thead><tbody>${rows.map(c=>`<tr class="client-row" data-key="${esc(c.id||c.source_key)}"><td><b>${esc(c.name)}</b></td><td>${esc(c.nif)}</td><td>${esc(c.district)}</td><td>${esc(c.phone)}</td><td>${esc(c.email)}</td><td>${esc(c.owner_name)}</td><td>${esc(c.source)}</td></tr>`).join('')}</tbody></table>`}
function bindClientRows(){qa('.client-row').forEach(r=>r.onclick=()=>editClient(r.dataset.key))}
function editClient(key){if(!connected)return needConfig();const c=clients.find(x=>String(x.id||x.source_key)===String(key))||{};openModal(key?'Editar cliente':'Criar cliente',`<div class="form-grid"><div class="field full"><label>Nome</label><input name="name" required value="${esc(c.name)}"></div><div><label>NIF</label><input name="nif" value="${esc(c.nif)}"></div><div><label>Distrito</label><input name="district" value="${esc(c.district)}"></div><div><label>Telefone</label><input name="phone" value="${esc(c.phone)}"></div><div><label>Email</label><input name="email" type="email" value="${esc(c.email)}"></div><div><label>Responsável</label><input name="owner_name" value="${esc(c.owner_name)}"></div><div class="field full"><label>Notas</label><textarea name="notes">${esc(c.notes)}</textarea></div></div><div class="form-actions">${c.id?'<button type="button" id="deactivateClient" class="danger">'+(c.active===false?'Reativar':'Desativar')+'</button>':''}<button type="button" class="secondary" onclick="document.getElementById('modalClose').click()">Cancelar</button><button class="accent">Guardar</button></div>`,async data=>{const payload={...data,source_key:c.source_key||data.nif||norm(data.name),updated_at:new Date().toISOString()};const res=c.id?await sb.from('crm_clients').update(payload).eq('id',c.id):await sb.from('crm_clients').insert(payload);if(res.error)throw res.error});if(c.id)$('deactivateClient').onclick=async()=>{const active=c.active===false;const {error}=await sb.from('crm_clients').update({active,updated_at:new Date().toISOString()}).eq('id',c.id);if(error)return alert(error.message);closeModal();await loadAll();renderClients()}}
function renderActivities(){$('view-activities').innerHTML=`<div class="toolbar"><h2>Atividades</h2><button id="newActivity" class="accent">+ Nova atividade</button></div><div class="panel">${activityTable(ownRows(activities))}</div>`;$('newActivity').onclick=()=>editActivity();qa('.activity-row').forEach(r=>r.onclick=()=>editActivity(r.dataset.id))}
function activityTable(rows){if(!rows.length)return '<div class="empty">Sem atividades.</div>';return `<div class="table-wrap"><table><thead><tr><th>Data</th><th>Tipo</th><th>Assunto</th><th>Cliente</th><th>Responsável</th><th>Estado</th></tr></thead><tbody>${rows.map(a=>`<tr class="activity-row" data-id="${a.id}"><td>${esc((a.starts_at||'').replace('T',' ').slice(0,16))}</td><td>${esc(a.type)}</td><td><b>${esc(a.subject)}</b></td><td>${esc(a.client_name)}</td><td>${esc(a.owner_name)}</td><td>${a.completed?'Concluída':'Pendente'}</td></tr>`).join('')}</tbody></table></div>`}
function editActivity(id){if(!connected)return needConfig();const a=activities.find(x=>String(x.id)===String(id))||{};openModal(id?'Editar atividade':'Nova atividade',`<div class="form-grid"><div><label>Tipo</label><select name="type">${getCfg('activity_types').map(x=>`<option ${x===a.type?'selected':''}>${esc(x)}</option>`).join('')}</select></div><div><label>Data e hora</label><input name="starts_at" type="datetime-local" required value="${(a.starts_at||'').slice(0,16)}"></div><div class="field full"><label>Assunto</label><input name="subject" required value="${esc(a.subject)}"></div><div><label>Cliente</label><input name="client_name" value="${esc(a.client_name)}"></div><div><label>Responsável</label>${ownerSelect(a.owner_id)}</div><div class="field full"><label>Notas</label><textarea name="notes">${esc(a.notes)}</textarea></div><div><label><input name="completed" type="checkbox" ${a.completed?'checked':''}> Concluída</label></div></div><div class="form-actions">${id?'<button type="button" id="deleteRecord" class="danger">Eliminar</button>':''}<button type="button" class="secondary" onclick="document.getElementById('modalClose').click()">Cancelar</button><button class="accent">Guardar</button></div>`,async data=>{data.completed=!!data.completed;data.owner_id=isAdmin?(data.owner_id||currentUser):currentUser;data.owner_name=USER_LABELS[data.owner_id]||data.owner_id;const res=id?await sb.from('crm_activities').update(data).eq('id',id):await sb.from('crm_activities').insert(data);if(res.error)throw res.error});if(id)$('deleteRecord').onclick=()=>deleteRow('crm_activities',id,'atividade')}
function renderCalendar(){const rows=ownRows(activities).slice().sort((a,b)=>String(a.starts_at).localeCompare(String(b.starts_at)));const grouped={};rows.forEach(a=>(grouped[(a.starts_at||'').slice(0,10)]??=[]).push(a));$('view-calendar').innerHTML=`<div class="toolbar"><h2>Calendário</h2><button id="calNew" class="accent">+ Adicionar</button></div><div class="grid">${Object.entries(grouped).map(([d,as])=>`<div class="panel"><h3>${new Date(d+'T12:00').toLocaleDateString('pt-PT',{weekday:'long',day:'2-digit',month:'long',year:'numeric'})}</h3>${activityTable(as)}</div>`).join('')||'<div class="panel empty">Sem eventos.</div>'}</div>`;$('calNew').onclick=()=>editActivity();qa('.activity-row').forEach(r=>r.onclick=()=>editActivity(r.dataset.id))}
function renderSettings(){if(!isAdmin)return;$('view-settings').innerHTML=`<div class="toolbar"><div><h2>Preferências CRM</h2><p>Área da Assistência/Administração: criar, editar, eliminar e ordenar opções.</p></div></div><div class="settings-grid">${['statuses','priorities','activity_types','loss_reasons'].map(k=>settingCard(k)).join('')}<div class="panel"><h3>Utilizadores CRM</h3><div class="setting-list">${profiles.map(p=>`<div class="setting-row"><span>${esc(p.display_name)} <small>(${esc(p.role)})</small></span><button class="secondary edit-profile" data-id="${p.id}">Editar</button><button class="danger del-profile" data-id="${p.id}">×</button></div>`).join('')}</div><button id="newProfile" style="margin-top:10px">+ Utilizador</button></div><div class="panel"><h3>Lembretes automáticos</h3>${Object.entries(getCfg('reminders')).map(([k,v])=>`<div class="field"><label>${esc(k)} — dias</label><input class="reminder-input" data-key="${esc(k)}" type="number" min="1" value="${v}"></div>`).join('')}<button id="saveReminders" class="accent" style="margin-top:10px">Guardar</button></div></div>`;qa('.setting-add').forEach(b=>b.onclick=()=>addSetting(b.dataset.key));qa('.setting-del').forEach(b=>b.onclick=()=>removeSetting(b.dataset.key,Number(b.dataset.i)));$('newProfile').onclick=()=>editProfile();qa('.edit-profile').forEach(b=>b.onclick=()=>editProfile(b.dataset.id));qa('.del-profile').forEach(b=>b.onclick=()=>deleteRow('crm_profiles',b.dataset.id,'utilizador'));$('saveReminders').onclick=()=>saveSetting('reminders',Object.fromEntries(qa('.reminder-input').map(i=>[i.dataset.key,Number(i.value)||1])))}
function settingCard(k){const labels={statuses:'Estados',priorities:'Prioridades',activity_types:'Tipos de atividade',loss_reasons:'Motivos de perda'};return `<div class="panel"><h3>${labels[k]}</h3><div class="setting-list">${getCfg(k).map((x,i)=>`<div class="setting-row"><span>${esc(x)}</span><span></span><button class="danger setting-del" data-key="${k}" data-i="${i}">×</button></div>`).join('')}</div><button class="setting-add" data-key="${k}" style="margin-top:10px">+ Adicionar</button></div>`}
async function addSetting(k){const v=prompt('Nova opção:');if(!v)return;await saveSetting(k,[...getCfg(k),v])}async function removeSetting(k,i){if(!confirm('Eliminar esta opção?'))return;const a=[...getCfg(k)];a.splice(i,1);await saveSetting(k,a)}async function saveSetting(k,v){if(!connected)return needConfig();const {error}=await sb.from('crm_settings').upsert({key:k,value:v,updated_at:new Date().toISOString()});if(error)return alert(error.message);await loadAll();renderSettings()}
function editProfile(id){if(!connected)return needConfig();const p=profiles.find(x=>x.id===id)||{};openModal(id?'Editar utilizador':'Criar utilizador',`<div class="form-grid"><div><label>Identificador</label><input name="id" ${id?'readonly':''} required value="${esc(p.id)}"></div><div><label>Nome</label><input name="display_name" required value="${esc(p.display_name)}"></div><div><label>Função</label><select name="role">${['assistencia','administrador','comercial'].map(x=>`<option ${x===p.role?'selected':''}>${x}</option>`).join('')}</select></div><div><label>Cor</label><input name="color" type="color" value="${p.color||'#0657ff'}"></div><div><label>Ativo</label><select name="active"><option value="true" ${p.active!==false?'selected':''}>Sim</option><option value="false" ${p.active===false?'selected':''}>Não</option></select></div></div><div class="form-actions"><button type="button" class="secondary" onclick="document.getElementById('modalClose').click()">Cancelar</button><button class="accent">Guardar</button></div>`,async data=>{data.active=data.active==='true';const res=await sb.from('crm_profiles').upsert(data);if(res.error)throw res.error})}
function openModal(title,html,onSave){$('modalTitle').textContent=title;$('modalForm').innerHTML=html;$('modal').classList.remove('hidden');$('modalForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),data={};for(const [k,v] of fd.entries())data[k]=v;qa('#modalForm input[type=checkbox]').forEach(i=>data[i.name]=i.checked);try{await onSave(data);closeModal();await loadAll();render(q('#tabs button.active').dataset.view)}catch(err){alert(err.message||err)}}}
function closeModal(){$('modal').classList.add('hidden');$('modalForm').innerHTML=''}
async function deleteRow(table,id,label){if(!connected)return needConfig();if(!confirm('Eliminar '+label+'? Esta ação fica registada no histórico.'))return;const {error}=await sb.from(table).delete().eq('id',id);if(error)return alert(error.message);closeModal();await loadAll();render(q('#tabs button.active').dataset.view)}
function needConfig(){alert('Configure primeiro o Supabase em CRM/supabase-config.js. O CRM não guarda registos no navegador.')}
document.addEventListener('DOMContentLoaded',setup);
})();
